<?php

namespace Database\Seeders;
use Faker\Factory as Faker;
use Hash;

use Illuminate\Database\Seeder;
use App\Models\Employee;

use Schema;
use DB;

class EmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // tambah satu user super admin
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        Employee::truncate();
        $employee                         = new Employee;
        $employee->code                   = 'EMP-00001';
        $employee->name                   = 'Admin';
        $employee->username               = 'superadmin';
        $employee->nik                    = 'superadmin';
        $employee->password               =  Hash::make('superadmin');
        $employee->email                  = 'pma_purchasing@pinusmerahabadi.co.id';
        $employee->save();

        $data = array(
            0 => array('name' => 'Hanung Purwo Utami', 'username' => 'Hanung Purwo Utami', 'nik' => '20214514', 'email' => 'hanung_purwo@pinusmerahabadi.co.id'),
            1 => array('name' => 'Andri Simeon Nomleni', 'username' => 'Andri Simeon Nomleni', 'nik' => '20171951', 'email' => 'andri_simeon@pinusmerahabadi.co.id'),
            2 => array('name' => 'Nurul Adi Prasetyo', 'username' => 'Nurul Adi Prasetyo', 'nik' => '20213609', 'email' => 'nurul_adi@pinusmerahabadi.co.id'),
            3 => array('name' => 'Husnul Hatimah', 'username' => 'Husnul Hatimah', 'nik' => '20200868', 'email' => 'husnul_hatimah@pinusmerahabadi.co.id'),
            4 => array('name' => 'Tjiang Kim Lan', 'username' => 'Tjiang Kim Lan', 'nik' => '15000255', 'email' => 'kim_lan@pinusmerahabadi.co.id'),
            5 => array('name' => 'Okta Riyuni BR Rambe', 'username' => 'Okta Riyuni BR Rambe', 'nik' => '20160070', 'email' => 'okta_riyuni@pinusmerahabadi.co.id'),
            6 => array('name' => 'Ricky Allen', 'username' => 'Ricky Allen', 'nik' => '18000988', 'email' => 'ricky_allen@pinusmerahabadi.co.id'),
            7 => array('name' => 'Roni Hamdani', 'username' => 'Roni Hamdani', 'nik' => '20140557', 'email' => 'roni_hamdani@pinusmerahabadi.co.id'),
            8 => array('name' => 'Cindy Oktavia Kurnia', 'username' => 'Cindy Oktavia', 'nik' => '17000177', 'email' => 'cindy_octavia@pinusmerahabadi.co.id'),
            9 => array('name' => 'Andrew Julianto', 'username' => 'Andrew Julianto', 'nik' => '18000218', 'email' => 'andrew_julianto@pinusmerahabadi.co.id'),
            10 => array('name' => 'Billy Supriady Lauwijaya', 'username' => 'Billy Supriadi', 'nik' => '05130052', 'email' => 'billy_supriady@pinusmerahabadi.co.id'),
            11 => array('name' => 'Andri Kustiansah', 'username' => 'Andri Kustiansah', 'nik' => '20140009', 'email' => 'andri_kustiansah@pinusmerahabadi.co.id'),
            12 => array('name' => 'Panji Sukma Yogaperwira', 'username' => 'Panji Sukma', 'nik' => '08140327', 'email' => 'panji_sukma@pinusmerahabadi.co.id'),
            13 => array('name' => 'Rizky Achmad Hidayat', 'username' => 'Rizky Achmad', 'nik' => '15000303', 'email' => 'rizky_achmad@pinusmerahabadi.co.id'),
            14 => array('name' => 'Ramdhan Rangganata Sudrajat', 'username' => 'Ramdhan Rangganata', 'nik' => '20162799', 'email' => 'ramdhan_rangganata@pinusmerahabadi.co.id'),
            15 => array('name' => 'Novilia Suhardi', 'username' => 'Novilia Suhardi', 'nik' => '17000651', 'email' => 'novilia_suhardi@pinusmerahabadi.co.id'),
            16 => array('name' => 'Imam Sudrajat', 'username' => 'Imam Sudrajat', 'nik' => '08131091', 'email' => 'imam_sudrajat@pinusmerahabadi.co.id'),
            17 => array('name' => 'Heru Widyantoro', 'username' => 'Heru Widyantoro', 'nik' => '08130688', 'email' => 'heru_widyantoro@pinusmerahabadi.co.id'),
            18 => array('name' => 'Abu Bakar', 'username' => 'Abu Bakar', 'nik' => '20191107', 'email' => 'abu_bakar@pinusmerahabadi.co.id'),
            19 => array('name' => 'Darsono', 'username' => 'Darsono', 'nik' => '20181327', 'email' => 'darsono@pinusmerahabadi.co.id'),
            20 => array('name' => 'Deris Siswanto', 'username' => 'Deris Siswanto', 'nik' => '20140490', 'email' => 'deris_siswanto@pinusmerahabadi.co.id'),
            21 => array('name' => 'Andriyana', 'username' => 'Andriyana', 'nik' => '20130061', 'email' => 'andryana@pinusmerahabadi.co.id'),
            22 => array('name' => 'Tandy Ferdian', 'username' => 'Tandy Ferdian', 'nik' => '21000157', 'email' => 'tandy_ferdian@pinusmerahabadi.co.id'),
            23 => array('name' => 'Noni Setia Rini', 'username' => 'Noni Setia Rini', 'nik' => '20190984', 'email' => 'noni_setia@pinusmerahabadi.co.id'),
            24 => array('name' => 'Supriyanto', 'username' => 'Supriyanto', 'nik' => '20181381', 'email' => 'supriyanto@pinusmerahabadi.co.id'),
            25 => array('name' => 'Arif Sadarudin', 'username' => 'Arif Sadarudin', 'nik' => '16000446', 'email' => 'arif_sadarudin@pinusmerahabadi.co.id'),
            26 => array('name' => 'Atika Nopita Sari', 'username' => 'Atika Nopita Sari', 'nik' => '20181329', 'email' => 'atika_nopita@pinusmerahabadi.co.id'),
            27 => array('name' => 'Hendra Maulana', 'username' => 'Hendra Maulana', 'nik' => '20183598', 'email' => 'hendra_maulana@pinusmerahabadi.co.id'),
            28 => array('name' => 'Yudhi Aryanatha. SA, S.Pi', 'username' => 'Yudhi Aryanatha. SA, S.Pi', 'nik' => '18000523', 'email' => 'yudhi_aryanatha@pinusmerahabadi.co.id'),
            29 => array('name' => 'Guruh Widhi Wasisto', 'username' => 'Guruh Widhi', 'nik' => '20203256', 'email' => 'guruh_widhi@pinusmerahabadi.co.id'),
            30 => array('name' => 'Any Fitriana', 'username' => 'Any Fitriana', 'nik' => '20182727', 'email' => 'any_fitriana@pinusmerahabadi.co.id'),
            31 => array('name' => 'I Kadek Agus Bambang Susila', 'username' => 'Kadek Agus Bambang', 'nik' => '17000363', 'email' => 'agus_bambang@pinusmerahabadi.co.id'),
            32 => array('name' => 'Sahriyati', 'username' => 'Sahriyati', 'nik' => '20171737', 'email' => 'sahriyati@pinusmerahabadi.co.id'),
            33 => array('name' => 'Syaiful Iskak', 'username' => 'Syaiful Iskak', 'nik' => '20140688', 'email' => 'syaiful_iskak@pinusmerahabadi.co.id'),
            34 => array('name' => 'Istin Mintarsih', 'username' => 'Istin Mintarsih', 'nik' => '20160419', 'email' => 'istin_mintarsih@pinusmerahabadi.co.id'),
            35 => array('name' => 'Esra Mariska Napitu', 'username' => 'Esra Mariska Napitu', 'nik' => '20151617', 'email' => 'esra_mariskan@pinusmerahabadi.co.id'),
            36 => array('name' => 'Hidayatur rahman', 'username' => 'Hidayaturahman', 'nik' => '20170045', 'email' => 'Hidayatur_rahman@pinusmerahabadi.co.id'),
            37 => array('name' => 'Sunarto', 'username' => 'Sunarto', 'nik' => '20172070', 'email' => 'sunarto@pinusmerahabadi.co.id'),
            38 => array('name' => 'Sofyan Saori', 'username' => 'Sofyan Saori', 'nik' => '20171636', 'email' => 'sofyan_saori@pinusmerahabadi.co.id'),
            39 => array('name' => 'Eka Yuliani', 'username' => 'Eka Yuliani', 'nik' => '20162515', 'email' => 'eka_yuliani@pinusmerahabadi.co.id'),
            40 => array('name' => 'Muhammad Junaidi', 'username' => 'Muhammad Junaidi', 'nik' => '20212014', 'email' => 'muhammad_junaidi@pinusmerahabadi.co.id'),
            41 => array('name' => 'Dedi Saputra', 'username' => 'Dedi Saputra', 'nik' => '16000381', 'email' => 'dedi_saputra@pinusmerahabadi.co.id'),
            42 => array('name' => 'Gusmardeko', 'username' => 'M. Gusmardeko', 'nik' => '16000137', 'email' => 'gusmardeko@pinusmerahabadi.co.id'),
            43 => array('name' => 'Bukran Hadi', 'username' => 'Bukran Hadi', 'nik' => '18000884', 'email' => 'bukran_hadi@pinusmerahabadi.co.id'),
            44 => array('name' => 'Donita T Manurung', 'username' => 'Donita T Manurung', 'nik' => '20180482', 'email' => 'donita_manurung@pinusmerahabadi.co.id'),
            45 => array('name' => 'Prada Syah Bekti Prawaca', 'username' => 'Prada Syah Bekti Prawaca', 'nik' => '20213074', 'email' => 'Prada_syah@pinusmerahabadi.co.id'),
            46 => array('name' => 'Danang Wicaksana', 'username' => 'Danang W', 'nik' => '20151949', 'email' => 'danang_wicaksana@pinusmerahabadi.co.id'),
            47 => array('name' => 'Ardiansyah Wijaya', 'username' => 'Ardiansyah Wijaya', 'nik' => '20181981', 'email' => 'ardiansyah_wijaya@pinusmerahabadi.co.id'),
            48 => array('name' => 'Edwansah', 'username' => 'Edwansah', 'nik' => '18000781', 'email' => 'edwansah@pinusmerahabadi.co.id'),
            49 => array('name' => 'Muhammad Iqbal Aziz Saputra', 'username' => 'Muhammad Iqbal Aziz Saputra', 'nik' => '20162472', 'email' => 'muhammad_iqbal@pinusmerahabadi.co.id'),
            50 => array('name' => 'Nur Atim', 'username' => 'Nur Atim', 'nik' => '05130057', 'email' => 'nur_atim@pinusmerahabadi.co.id'),
            51 => array('name' => 'Kristian Prihatmoko', 'username' => 'Kristian Prihatmoko', 'nik' => '20210932', 'email' => 'kristian_prihatmoko@pinusmerahabadi.co.id'),
            52 => array('name' => 'Panji Gemuruh', 'username' => 'Panji Gemuruh', 'nik' => '20140173', 'email' => 'panji_gemuruh@pinusmerahabadi.co.id'),
            53 => array('name' => 'Fika Adriani', 'username' => 'Fika Adriani', 'nik' => '20180723', 'email' => 'fika_adriani@pinusmerahabadi.co.id'),
            54 => array('name' => 'Nur Fadilah R.', 'username' => 'Nur Fadilah R', 'nik' => '20200843', 'email' => 'nur_fadilah@pinusmerahabadi.co.id'),
            55 => array('name' => 'Athanasius Patero Aripaska', 'username' => 'Athanasius Patero Aripaska', 'nik' => '20191819', 'email' => 'athanasius_patero@pinusmerahabadi.co.id'),
            56 => array('name' => 'Depi Satrio', 'username' => 'Depi Satrio', 'nik' => '20201706', 'email' => 'depi_satrio@pinusmerahabadi.co.id'),
            57 => array('name' => 'Viona Natasha', 'username' => 'Viona', 'nik' => '20211850', 'email' => 'viona_natasha@pinusmerahabadi.co.id'),
            58 => array('name' => 'Surya Dharma', 'username' => 'Surya Dharma', 'nik' => '16000379', 'email' => 'surya_dharma@pinusmerahabadi.co.id'),
            59 => array('name' => 'Diana', 'username' => 'Diana', 'nik' => '20173120', 'email' => 'diana@pinusmerahabadi.co.id'),
            60 => array('name' => 'Heri Istadianto', 'username' => 'Heri Istadianto', 'nik' => '20170402', 'email' => 'heri_istadianto@pinusmerahabadi.co.id'),
            61 => array('name' => 'Hendi Bahtiar', 'username' => 'Hendi Bahtiar', 'nik' => '20173753', 'email' => 'hendi_bahtiar@pinusmerahabadi.co.id'),
            62 => array('name' => 'Edi Sukarni', 'username' => 'Edi Sukarni', 'nik' => '16000331', 'email' => 'edi_sukarni@pinusmerahabadi.co.id'),
            63 => array('name' => 'Pepita Rahmanita', 'username' => 'Pepita Rahmanita', 'nik' => '20160005', 'email' => 'pepita_rahmanita@pinusmerahabadi.co.id'),
            64 => array('name' => 'Rizal Maulana Yusuf', 'username' => 'Rizal Maulana', 'nik' => '20170759', 'email' => 'rizal_maulana@pinusmerahabadi.co.id'),
            65 => array('name' => 'Tarmidi', 'username' => 'Tarmidi', 'nik' => '21000111', 'email' => 'tarmidi@pinusmerahabadi.co.id'),
            66 => array('name' => 'Aang Suherman', 'username' => 'Aang Suherman', 'nik' => '19000319', 'email' => 'aang_suherman@pinusmerahabadi.co.id'),
            67 => array('name' => 'Roni Irawan', 'username' => 'Roni Irawan', 'nik' => '20150375', 'email' => 'roni_irawan@pinusmerahabadi.co.id'),
            68 => array('name' => 'Hendra Suwandi', 'username' => 'Hendra Suwandi', 'nik' => '20130337', 'email' => 'hendra_suwandi@pinusmerahabadi.co.id'),
            69 => array('name' => 'Frastika', 'username' => 'Frastika', 'nik' => '20200670', 'email' => 'frastika@pinusmerahabadi.co.id'),
            70 => array('name' => 'Suntoko', 'username' => 'Suntoko', 'nik' => '20130295', 'email' => 'suntoko@pinusmerahabadi.co.id'),
            71 => array('name' => 'Ade Nalim', 'username' => 'Ade Nalim', 'nik' => '20162887', 'email' => 'ade_nalim@pinusmerahabadi.co.id'),
            72 => array('name' => 'Intan Nurcahya', 'username' => 'Intan Nurcahya', 'nik' => '20181268', 'email' => 'intan_nurcahya@pinusmerahabadi.co.id'),
            73 => array('name' => 'Windra Jaya Lay', 'username' => 'Windra Jaya Lay', 'nik' => '17000646', 'email' => 'windra_jaya@pinusmerahabadi.co.id'),
            74 => array('name' => 'Afit Nurrohman', 'username' => 'Afit Nurrohman', 'nik' => '20180773', 'email' => 'afit_nurrohman@pinusmerahabadi.co.id'),
            75 => array('name' => 'Yosep', 'username' => 'Yosep', 'nik' => '20214502', 'email' => 'yosep_unggara@pinusmerahabadi.co.id'),
            76 => array('name' => 'Nabil', 'username' => 'Nabil', 'nik' => '18000317', 'email' => 'nabil@pinusmerahabadi.co.id'),
            77 => array('name' => 'Arifudin', 'username' => 'Arifudin', 'nik' => '20172815', 'email' => 'arifudin@pinusmerahabadi.co.id'),
            78 => array('name' => 'Sherly Lucyana', 'username' => 'Sherly Lucyana', 'nik' => '20183585', 'email' => 'sherly_lucyana@pinusmerahabadi.co.id'),
            79 => array('name' => 'Bayu', 'username' => 'Bayu', 'nik' => '20140516', 'email' => 'bayu@pinusmerahabadi.co.id'),
            80 => array('name' => 'Yuliandi', 'username' => 'Yuliandi', 'nik' => '20183314', 'email' => 'yuliandi@pinusmerahabadi.co.id'),
            81 => array('name' => 'Budi Hardiansyah', 'username' => 'Budi Hardiansyah', 'nik' => '20163091', 'email' => 'budi_hardiansyah@pinusmerahabadi.co.id'),
            82 => array('name' => 'Silmy Salamatun Nisaa', 'username' => 'Silmy Salamatun Nisaa', 'nik' => '20130374', 'email' => 'silmy_salamatun@pinusmerahabadi.co.id'),
            83 => array('name' => 'Sri Rahayu Ningsih', 'username' => 'Sri Rahayu Ningsih', 'nik' => '20130320', 'email' => 'sri_rahayu@pinusmerahabadi.co.id'),
            84 => array('name' => 'Cecep Mulyawan', 'username' => 'Cecep Mulyawan', 'nik' => '20160401', 'email' => 'cecep_mulyawan@pinusmerahabadi.co.id'),
            85 => array('name' => 'Uki Marjuki', 'username' => 'Uki Marjuki', 'nik' => '16000178', 'email' => 'uki_marjuki@pinusmerahabadi.co.id'),
            86 => array('name' => 'Iman Firmansyah', 'username' => 'Iman Firmansyah', 'nik' => '20173168', 'email' => 'iman_firmansyah@pinusmerahabadi.co.id'),
            87 => array('name' => 'Wisnu Broto', 'username' => 'Wisnu Broto', 'nik' => '20160444', 'email' => 'wisnu_broto@pinusmerahabadi.co.id'),
            88 => array('name' => 'Asmayulita', 'username' => 'Asmayulita', 'nik' => '20172629', 'email' => 'asmayulita@pinusmerahabadi.co.id'),
            89 => array('name' => 'Novayana Purba', 'username' => 'Novayana Purba', 'nik' => '16000327', 'email' => 'novayana_purba@pinusmerahabadi.co.id'),
            90 => array('name' => 'Jenny Jap', 'username' => 'Jenny Jap', 'nik' => '17000599', 'email' => 'jenny_jap@pinusmerahabadi.co.id'),
            91 => array('name' => 'Andrew', 'username' => 'Andrew', 'nik' => '17000650', 'email' => 'andrew@pinusmerahabadi.co.id'),
            92 => array('name' => 'Heppy Putri Fatimah', 'username' => 'Heppy Putri Fatimah', 'nik' => '20182666', 'email' => 'heppy_putri@pinusmerahabadi.co.id'),
            93 => array('name' => 'Khoirul Anam', 'username' => 'Khoirul Anam', 'nik' => '20171839', 'email' => 'khoirul_anam@pinusmerahabadi.co.id'),
            94 => array('name' => 'Sumarni', 'username' => 'Sumarni', 'nik' => '20181700', 'email' => 'sumarni_ani@pinusmerahabadi.co.id'),
            95 => array('name' => 'Kadek Ayu Sudiartini', 'username' => 'Kadek Ayu Sudiartini', 'nik' => '20150148', 'email' => 'ayu_sudiartini@pinusmerahabadi.co.id'),
            96 => array('name' => 'Putu Indra Budhiwan Regig', 'username' => 'Putu Indra Budhiwan Regig', 'nik' => '16000248', 'email' => 'putu_indra@pinusmerahabadi.co.id'),
            97 => array('name' => 'Gede Nesa Eka Yasti', 'username' => 'Gede Nesa Eka Yasti', 'nik' => '16000033', 'email' => 'gede_nesa@pinusmerahabadi.co.id'),
            98 => array('name' => 'Ernest Christian Doerleben', 'username' => 'Ernest Christian', 'nik' => '05130037', 'email' => 'ernest_christian@pinusmerahabadi.co.id'),
            99 => array('name' => 'Anak Agung Putu Juli Ardika', 'username' => 'Anak Agung Putu Juli Ardika', 'nik' => '20202245', 'email' => 'agung_putu@pinusmerahabadi.co.id'),
            100 => array('name' => 'Septian Rinaldy', 'username' => 'Septian Rinaldy', 'nik' => '20171622', 'email' => 'septian_rinaldy@pinusmerahabadi.co.id'),
            101 => array('name' => 'Nixon Yoshua Kodongan', 'username' => 'Nixon Kodongan', 'nik' => '15000367', 'email' => 'nixon_kodongan@pinusmerahabadi.co.id'),
            102 => array('name' => 'Neng Yuyun Safitri', 'username' => 'Neng Yuyun Safitri', 'nik' => '20130082', 'email' => 'yuyun_safitri@pinusmerahabadi.co.id'),
            103 => array('name' => 'Dista Andriani Yunida', 'username' => 'Dista Andriani Yunida', 'nik' => '20180404', 'email' => 'dista_andriani@pinusmerahabadi.co.id'),
            104 => array('name' => 'Ervan Adhi Saputra', 'username' => 'Ervan Adhi', 'nik' => '08140388', 'email' => 'ervan_adhi@pinusmerahabadi.co.id'),
            105 => array('name' => 'Bambang Hermanto', 'username' => 'Bambang Hermanto', 'nik' => '05130083', 'email' => 'bambang_hermanto@pinusmerahabadi.co.id'),
            106 => array('name' => 'Heri Bertus Iwan Kristiawan', 'username' => 'Heri Bertus Iwan Kristiawan', 'nik' => '05130054', 'email' => 'heribertus_iwan@pinusmerahabadi.co.id'),
            107 => array('name' => 'Hafid Fauzi Sophian', 'username' => 'Hafid Fauzi', 'nik' => '08130379', 'email' => 'hafid_fauzi@pinusmerahabadi.co.id'),
            108 => array('name' => 'Nia Astarina', 'username' => 'Nia Astarina', 'nik' => '20211423', 'email' => 'nia_astarina@pinusmerahabadi.co.id'),
            109 => array('name' => 'Awang Nepriyanto', 'username' => 'Awang Nepriyanto', 'nik' => '20160546', 'email' => 'awang_nepriyanto@pinusmerahabadi.co.id'),
            110 => array('name' => 'Rian Hasan, SE', 'username' => 'Rian Hasan', 'nik' => '20211773', 'email' => 'rian_hasan@pinusmerahabadi.co.id'),
            111 => array('name' => 'Agung Purwanto', 'username' => 'Agung Purwanto', 'nik' => '20163415', 'email' => 'agung_purwanto@pinusmerahabadi.co.id'),
            112 => array('name' => 'Dody Setyawan', 'username' => 'Dody Setyawan', 'nik' => '16000027', 'email' => 'dody_setyawan@pinusmerahabadi.co.id'),
            113 => array('name' => 'Tirani Susanti', 'username' => 'Susan', 'nik' => '17000054', 'email' => 'tirani_susanti@pinusmerahabadi.co.id'),
            114 => array('name' => 'Anugrah Purnama', 'username' => 'Anugrah', 'nik' => '20200299', 'email' => 'anugrah_purnama@pinusmerahabadi.co.id'),
            115 => array('name' => 'Deny Rachmat', 'username' => 'Deny', 'nik' => '20163142', 'email' => 'deny@pinusmerahabadi.co.id'),
            116 => array('name' => 'Victor Simbolon', 'username' => 'Victor', 'nik' => '20182674', 'email' => 'pmaho_purchasing1@pinusmerahabadi.co.id'),
            117 => array('name' => 'Erwin Syah Fauzan', 'username' => 'Erwin', 'nik' => '20183771', 'email' => 'pmaho_purchasing2@pinusmerahabadi.co.id'),
            118 => array('name' => 'Zehan Fahma Ahmad Hidayat', 'username' => 'Zehan', 'nik' => '20214131', 'email' => 'pmaho_purchasing3@pinusmerahabadi.co.id'),
            119 => array('name' => 'Wiwik Endang Wijaya', 'username' => 'Wiwik Wijaya', 'nik' => '16000445', 'email' => 'wiwik_wijaya@pinusmerahabadi.co.id'),
            120 => array('name' => 'Novi Oktavia Dewi Sari', 'username' => 'Novi Oktavia', 'nik' => '20140524', 'email' => 'novi_oktavia@pinusmerahabadi.co.id'),
            121 => array('name' => 'Grace Avianny', 'username' => 'Grace Avianny', 'nik' => '15000215', 'email' => 'grace_avianny@pinusmerahabadi.co.id'),
            122 => array('name' => 'Hardiyansah', 'username' => 'Hardi', 'nik' => '20000116', 'email' => 'hardiyansah@pinusmerahabadi.co.id'),
            123 => array('name' => 'Ervyanty Oktaviani', 'username' => 'Ervy', 'nik' => '20140699', 'email' => 'ervyanty_oktaviani@pinusmerahabadi.co.id'),
            124 => array('name' => 'Muhammad Iqbal Al-Kahfi', 'username' => 'Iqbal Al Kahfi', 'nik' => '20171313', 'email' => 'iqbal_alkahfi@pinusmerahabadi.co.id'),
            125 => array('name' => 'Dhea Agatha Cornelia', 'username' => 'Dhea', 'nik' => '20200499', 'email' => 'dhea_agatha@pinusmerahabadi.co.id'),
            126 => array('name' => 'Putri Girianti', 'username' => 'Putri', 'nik' => '20190981', 'email' => 'putri_girianti@pinusmerahabadi.co.id'),
            127 => array('name' => 'Rina Permata Sari', 'username' => 'Rina', 'nik' => '20180386', 'email' => 'rina_permatasari@pinusmerahabadi.co.id'),
            128 => array('name' => 'Marisa Udurma Hasiana', 'username' => 'Marisa', 'nik' => '16000214', 'email' => 'marisa_udurma@pinusmerahabadi.co.id'),
            129 => array('name' => 'Futri Lestari Sagala', 'username' => 'Futri', 'nik' => '21000212', 'email' => 'futri_lestari@pinusmerahabadi.co.id'),
            130 => array('name' => 'Dwi Kemala Putri', 'username' => 'Dwi Kemala', 'nik' => '20161720', 'email' => 'dwi_kemala@pinusmerahabadi.co.id'),
            131 => array('name' => 'Agustini Sihombing', 'username' => 'Agustini', 'nik' => '20182489', 'email' => 'agustini_sihombing@pinusmerahabadi.co.id'),
            132 => array('name' => 'Efraim Yeremia Putra Sihombing', 'username' => 'Efraim', 'nik' => '20183282', 'email' => 'efraim_yeremia@pinusmerahabadi.co.id'),
            133 => array('name' => 'San San Koespriyanti', 'username' => 'San San Koespriyanti', 'nik' => '17000748', 'email' => 'sansan_yanti@pinusmerahabadi.co.id'),
            134 => array('name' => 'Indah Purnamasari', 'username' => 'Indah', 'nik' => '20160117', 'email' => 'indah_purnamasari@pinusmerahabadi.co.id'),
            135 => array('name' => 'Lina Nurul Fadhilah', 'username' => 'Lina', 'nik' => '20160034', 'email' => 'lina_nurul@pinusmerahabadi.co.id'),
            136 => array('name' => 'Irfan Farma Sinaga', 'username' => 'Irfan Farma', 'nik' => '20170725', 'email' => 'irfan_farma@pinusmerahabadi.co.id'),
            137 => array('name' => 'Dina Nurul Chotimah', 'username' => 'Dina Chotimah', 'nik' => '18000782', 'email' => 'dina_chotimah@pinusmerahabadi.co.id'),
            138 => array('name' => 'Muhammad Bayu Sofiyulloh', 'username' => 'Muhammad Bayu Sofiyulloh', 'nik' => '20000202', 'email' => 'muhammad_bayu@pinusmerahabadi.co.id'),
            139 => array('name' => 'Rai Rukmana', 'username' => 'Rai', 'nik' => '20190682', 'email' => 'rai_rukmana@pinusmerahabadi.co.id'),
            140 => array('name' => 'Okiyandi Wiyantara', 'username' => 'Oki Riyandi', 'nik' => '20180762', 'email' => 'okiyandi_wiyantara@pinusmerahabadi.co.id'),
            141 => array('name' => 'Rifqy Reza Rachmansyah', 'username' => 'Reza', 'nik' => '20170547', 'email' => 'reza_rachmansyah@pinusmerahabadi.co.id'),
            142 => array('name' => 'Indriyana Solihin', 'username' => 'Indri', 'nik' => '20151302', 'email' => 'indriyana_solihin@pinusmerahabadi.co.id'),
            143 => array('name' => 'Puput Melati', 'username' => 'Puput', 'nik' => '20183340', 'email' => 'puput_melati@pinusmerahabadi.co.id'),
            144 => array('name' => 'John Simon Purba', 'username' => 'John Simon', 'nik' => '08140837', 'email' => 'john_simon@pinusmerahabadi.co.id'),
            145 => array('name' => 'Tjin Patrecia', 'username' => 'Patrice', 'nik' => '15000226', 'email' => 'tjin_patrice@pinusmerahabadi.co.id'),
            146 => array('name' => 'Katrin Pamela', 'username' => 'Katrin', 'nik' => '20150180', 'email' => 'katrin_pamela@pinusmerahabadi.co.id'),
            147 => array('name' => 'Johanes', 'username' => 'Johanes', 'nik' => '15000078', 'email' => 'johanes@pinusmerahabadi.co.id'),
            148 => array('name' => 'Andria Oki Bastian', 'username' => 'Andria Bastian', 'nik' => '18000140', 'email' => 'andria_bastian@pinusmerahabadi.co.id'),
            149 => array('name' => 'David', 'username' => 'David Iskandar', 'nik' => '08140836', 'email' => 'david_iskandar@pinusmerahabadi.co.id'),
            150 => array('name' => 'James Arthur Anggawinata', 'username' => 'James Arthur', 'nik' => '08141504', 'email' => 'james_arthur@pinusmerahabadi.co.id'),
            151 => array('name' => 'Susilawati', 'username' => 'Susilawati', 'nik' => '16000348', 'email' => 'susilawati@pinusmerahabadi.co.id'),
            152 => array('name' => 'Dwita Riyanti', 'username' => 'Dwita', 'nik' => '20191197', 'email' => 'dwita_riyanti@pinusmerahabadi.co.id'),
            153 => array('name' => 'Mahdi Maulana Yusup', 'username' => 'Maul', 'nik' => '20200592', 'email' => 'pmaho_ga2@pinusmerahabadi.co.id'),
            154 => array('name' => 'Yusticia Yusup Hakimi', 'username' => 'Yus', 'nik' => '20161729', 'email' => 'pmaho_ga4@pinusmerahabadi.co.id'),
            155 => array('name' => 'Besler Sorin Parlindungan Pasaribu', 'username' => 'Besler Pasaribu', 'nik' => '20163021', 'email' => 'besler_pasaribu@pinusmerahabadi.co.id'),
            156 => array('name' => 'Siti Hardiyanti Fauziah', 'username' => 'Siti Hardiyanti Fauziah', 'nik' => '20160040', 'email' => 'hardiyanti_fauziyah@pinusmerahabadi.co.id'),
            157 => array('name' => 'Chintia Laras', 'username' => 'Chintia Laras', 'nik' => '20160640', 'email' => 'chintia_laras@pinusmerahabadi.co.id'),
            158 => array('name' => 'Suhardi Suar Ningrat Laiya', 'username' => 'Suhardi Laiya', 'nik' => '16000414', 'email' => 'suhardi_laiya@pinusmerahabadi.co.id'),
            159 => array('name' => 'Ahmad Naqieb Alinaksi', 'username' => 'Ahmad Naqieb Alinaksi', 'nik' => '18000049', 'email' => 'ahmad_naqieb@pinusmerahabadi.co.id'),
            160 => array('name' => 'Riki Kristiana', 'username' => 'Riki Kristiana', 'nik' => '18000353', 'email' => 'riki_kristiana@pinusmerahabadi.co.id'),
            161 => array('name' => 'Dania Arifani', 'username' => 'Dania Arifani', 'nik' => '08130327', 'email' => 'dania_arifani@pinusmerahabadi.co.id'),
            162 => array('name' => 'Muhammad Dharma Nusantara', 'username' => 'Muhammad Dharma Nusantara', 'nik' => '20210457', 'email' => 'dharma_nusantara@pinusmerahabadi.co.id'),
            163 => array('name' => 'Origen Morris Sileng', 'username' => 'Origen Morris Sileng', 'nik' => '20183320', 'email' => 'origen_morris@pinusmerahabadi.co.id'),
            164 => array('name' => 'Windy Betalyana', 'username' => 'Windy Betalyana', 'nik' => '20162490', 'email' => 'windy@pinusmerahabadi.co.id'),
            165 => array('name' => 'Wiwin Kurnia', 'username' => 'Wiwin Kurnia', 'nik' => '18000596', 'email' => 'wiwin_kurnia@pinusmerahabadi.co.id'),
            166 => array('name' => 'Nova Adhista', 'username' => 'Nova Adhista', 'nik' => '20183245', 'email' => 'nova_adhista@pinusmerahabadi.co.id'),
            167 => array('name' => 'Evi Rosbayeni', 'username' => 'Evi Rosbayeni', 'nik' => '20150406', 'email' => 'evi_rosbayeni@pinusmerahabadi.co.id'),
            168 => array('name' => 'Rosti Ardi Utami', 'username' => 'Rosti Ardi Utami', 'nik' => '20190338', 'email' => 'pmaho_bse-idrws@pinusmerahabadi.co.id'),
            169 => array('name' => 'Agun Witjaksono', 'username' => 'Agun Witjaksono', 'nik' => '20173149', 'email' => 'agun_witjaksono@pinusmerahabadi.co.id'),
            170 => array('name' => 'Irfan Riadi', 'username' => 'Irfan Riadi', 'nik' => '20151064', 'email' => 'irfan_riadi@pinusmerahabadi.co.id'),
            171 => array('name' => 'Ririn Iktianuari', 'username' => 'Ririn Iktianuari', 'nik' => '20140517', 'email' => 'ririn_iktianuri@pinusmerahabadi.co.id'),
            172 => array('name' => 'Nova Apriwaty Sinuraya', 'username' => 'Nova Apriwaty Sinuraya', 'nik' => '20180449', 'email' => 'nova_apriwaty@pinusmerahabadi.co.id'),
            173 => array('name' => 'Agus Nur Sholeh', 'username' => 'Agus Nur Sholeh', 'nik' => '08140802', 'email' => 'agus_nursholeh@pinusmerahabadi.co.id'),
            174 => array('name' => 'Jefri Setiadi Tedja', 'username' => 'Jefri Setiadi Tedja', 'nik' => '17000652', 'email' => 'jefri_setiadi@pinusmerahabadi.co.id'),
            175 => array('name' => 'Dewi Sulistyaningrum', 'username' => 'Dewi Sulistyaningrum', 'nik' => '18000855', 'email' => 'dewi_sulistyaningrum@pinusmerahabadi.co.id'),
            176 => array('name' => 'Marsella Triwahyuni', 'username' => 'Marsella Triwahyuni', 'nik' => '16000336', 'email' => 'marsella_triwahyuni@pinusmerahabadi.co.id'),
            177 => array('name' => 'Alexander', 'username' => 'Alexander', 'nik' => '17000648', 'email' => 'alexander@pinusmerahabadi.co.id'),
            178 => array('name' => 'Agung Rizky Adnan', 'username' => 'Agung Rizky Adnan', 'nik' => '20171803', 'email' => 'agung_rizky@pinusmerahabadi.co.id'),
            179 => array('name' => 'Bayhaqi', 'username' => 'Bayhaqi', 'nik' => '20150642', 'email' => 'bayhaqi@pinusmerahabadi.co.id'),
            180 => array('name' => 'Achmad Wira Wiguna', 'username' => 'Achmad Wira Wiguna', 'nik' => '17000746', 'email' => 'wira_wiguna@pinusmerahabadi.co.id'),
            181 => array('name' => 'Andi Permana', 'username' => 'Andi Permana', 'nik' => '20170804', 'email' => 'andi_permana@pinusmerahabadi.co.id'),
            182 => array('name' => 'Asep Kiki Abdul Aziz', 'username' => 'Asep Kiki Abdul Aziz', 'nik' => '20210988', 'email' => 'asep_kiki@pinusmerahabadi.co.id'),
            183 => array('name' => 'Ade Firmansyah', 'username' => 'Ade Firmansyah', 'nik' => '20140261', 'email' => 'ade_firmansyah@pinusmerahabadi.co.id'),
            184 => array('name' => 'Rachmad Wibawa', 'username' => 'Rachmad Wibawa', 'nik' => '20172039', 'email' => 'rachmad_wibawa@pinusmerahabadi.co.id'),
            185 => array('name' => 'Rusiyati', 'username' => 'Rusiyati', 'nik' => '20130019', 'email' => 'rusiyati@pinusmerahabadi.co.id'),
            186 => array('name' => 'Widarto Juni Triatmoko', 'username' => 'Widarto Juni', 'nik' => '16000250', 'email' => 'widarto_triatmoko@pinusmerahabadi.co.id'),
            187 => array('name' => 'Aninda Narulita Situmorang', 'username' => 'Aninda Situmorang', 'nik' => '18000213', 'email' => 'aninda_situmorang@pinusmerahabadi.co.id'),
            188 => array('name' => 'Toni Kurniawan', 'username' => 'Toni K', 'nik' => '20000179', 'email' => 'tony_kurniawan@pinusmerahabadi.co.id'),
            189 => array('name' => 'Dirham Rivai', 'username' => 'Dirham Rivai', 'nik' => '08140328', 'email' => 'dirham_rivai@pinusmerahabadi.co.id'),
            190 => array('name' => 'Andrian Masunggang', 'username' => 'Andrian M', 'nik' => '20182091', 'email' => 'andrian_masunggang@pinusmerahabadi.co.id'),
            191 => array('name' => 'Sucen Aprilyansyah Fauzi', 'username' => 'Sucen Aprilyansyah Fauzi', 'nik' => '20180238', 'email' => 'sucen_fauzi@pinusmerahabadi.co.id'),
            192 => array('name' => 'Muhammad Ridlo', 'username' => 'Muhammad Ridlo', 'nik' => '20000180', 'email' => 'muhammad_ridlo@pinusmerahabadi.co.id'),
            193 => array('name' => 'Wisnu Ariadji', 'username' => 'Wisnu Ariadji', 'nik' => '18000052', 'email' => 'wisnu_ariadji@pinusmerahabadi.co.id'),
            194 => array('name' => 'Antie Setiyati', 'username' => 'Antie Setiyati', 'nik' => '20070001', 'email' => 'antie_setiyati@pinusmerahabadi.co.id'),
            195 => array('name' => 'Deny Rachmat', 'username' => 'Deny Rachmat', 'nik' => '08140131', 'email' => 'deny_rachmat@pinusmerahabadi.co.id'),
            196 => array('name' => 'Supardi', 'username' => 'Supardi', 'nik' => '17000121', 'email' => 'supardi@pinusmerahabadi.co.id'),
            197 => array('name' => 'Shanti Yuliana', 'username' => 'Shanti Yuliana', 'nik' => '20164310', 'email' => 'shanti_yuliana@pinusmerahabadi.co.id'),
            198 => array('name' => 'Hari Nurdiansyah', 'username' => 'Hari Nurdiansyah', 'nik' => '20140374', 'email' => 'hari_nurdiansyah@pinusmerahabadi.co.id'),
            199 => array('name' => 'Ratna Dewi Mayasari Yudhaningtyas, S.Pt', 'username' => 'Ratna Dewi Mayasari Yudhaningtyas, S.Pt', 'nik' => '20161942', 'email' => 'ratna_dewi@pinusmerahabadi.co.id'),
            200 => array('name' => 'Catur Prasetyo', 'username' => 'Catur Prasetyo', 'nik' => '20213577', 'email' => 'catur_prasetyo@pinusmerahabadi.co.id'),
            201 => array('name' => 'Irawan Nurdiansyah', 'username' => 'Irawan Nurdiansyah', 'nik' => '20140324', 'email' => 'irawan@pinusmerahabadi.co.id'),
            202 => array('name' => 'Abdur Rohman', 'username' => 'Abdur Rohman', 'nik' => '20190334', 'email' => 'abdur_rohman@pinusmerahabadi.co.id'),
            203 => array('name' => 'Nanda Setiawan Dewi', 'username' => 'Nanda Setiawan Dewi', 'nik' => '20172918', 'email' => 'nanda_setiawan@pinusmerahabadi.co.id'),
            204 => array('name' => 'Daud Agus Setyono', 'username' => 'Daud Agus S', 'nik' => '20130229', 'email' => 'daud_as@pinusmerahabadi.co.id'),
            205 => array('name' => 'Andri Wijaya', 'username' => 'Andri Wijaya', 'nik' => '20202811', 'email' => 'andri_wijaya@pinusmerahabadi.co.id'),
            206 => array('name' => 'Muhammad Novri Wanjaya', 'username' => 'Novri Wanjaya', 'nik' => '20000072', 'email' => 'novri_wanjaya@pinusmerahabadi.co.id'),
            207 => array('name' => 'Teguh Dwi Christina', 'username' => 'Teguh Dwichristina', 'nik' => '20163366', 'email' => 'teguh_dwichristina@pinusmerahabadi.co.id'),
            208 => array('name' => 'Agung Gunandar', 'username' => 'Agung Gunandar', 'nik' => '20161381', 'email' => 'agung_gunandar@pinusmerahabadi.co.id'),
            209 => array('name' => 'Andrian Saputra', 'username' => 'Andrian Saputra', 'nik' => '20152021', 'email' => 'andrian_saputra@pinusmerahabadi.co.id'),
            210 => array('name' => 'Tri Parwita Sugianto', 'username' => 'Tri Parwita', 'nik' => '20151233', 'email' => 'tri_parwita@pinusmerahabadi.co.id'),
            211 => array('name' => 'Ade Mulyana', 'username' => 'Ade Mulyana', 'nik' => '15000107', 'email' => 'ade_mulyana@pinusmerahabadi.co.id'),
            212 => array('name' => 'Samsul Aripin', 'username' => 'Samsul Aripin', 'nik' => '20191945', 'email' => 'samsul_aripin@pinusmerahabadi.co.id'),
            213 => array('name' => 'Adi Sampurno', 'username' => 'Adi Sampurno', 'nik' => '16000177', 'email' => 'adi_sampurno@pinusmerahabadi.co.id'),
            214 => array('name' => 'Muhamad Nasrum', 'username' => 'Nasrum', 'nik' => '16000136', 'email' => 'nasrum@pinusmerahabadi.co.id'),
            215 => array('name' => 'La Sabara', 'username' => 'La Sabara', 'nik' => '16000080', 'email' => 'sabara@pinusmerahabadi.co.id'),
            216 => array('name' => 'Mashadi', 'username' => 'Mashadi', 'nik' => '20191906', 'email' => 'mashadi@pinusmerahabadi.co.id'),
            217 => array('name' => 'Albert Parningotan Sinurat', 'username' => 'Albert Parningotan Sinurat', 'nik' => '20140466', 'email' => 'albert_sinurat@pinusmerahabadi.co.id'),
            218 => array('name' => 'Hartono', 'username' => 'Hartono', 'nik' => '20140267', 'email' => 'hartono@pinusmerahabadi.co.id'),
            219 => array('name' => 'I Putu Kariawan', 'username' => 'I Putu Kariawan', 'nik' => '20161305', 'email' => 'agus_wiyadnyana@pinusmerahabadi.co.id'),
            220 => array('name' => 'Laode Emha Alfasril Sampaga', 'username' => 'Laode Emha Alfasril Sampaga', 'nik' => '20212482', 'email' => 'laode_emha@pinusmerahabadi.co.id'),
            221 => array('name' => 'Sella Ambrina', 'username' => 'Sella Ambrina', 'nik' => '20201148', 'email' => 'sella_ambrina@pinusmerahabadi.co.id'),
            222 => array('name' => 'Heri Bando Setiawan', 'username' => 'Heri Bando Setiawan', 'nik' => '20160848', 'email' => 'heri_setiawan@pinusmerahabadi.co.id'),
            223 => array('name' => 'Agus Santoso', 'username' => 'Agus Santoso', 'nik' => '08131251', 'email' => 'agus_santoso@pinusmerahabadi.co.id'),
            224 => array('name' => 'Sidik Ahmad Maulana', 'username' => 'Sidik Ahmad Maulana', 'nik' => '20130293', 'email' => 'sidik_ahmad@pinusmerahabadi.co.id'),
            225 => array('name' => 'Dimas Yudha Pratama', 'username' => 'Dimas Yudha Pratama', 'nik' => '20164281', 'email' => 'dimas_yudha@pinusmerahabadi.co.id'),
            226 => array('name' => 'Misgianto', 'username' => 'Misgianto', 'nik' => '20163361', 'email' => 'misgianto@pinusmerahabadi.co.id'),
            227 => array('name' => 'Eka Handayani', 'username' => 'Eka Handayani', 'nik' => '20210285', 'email' => 'eka_handayani@pinusmerahabadi.co.id'),
            228 => array('name' => 'Edy Kurniawan Winoto', 'username' => 'Edi Kurniawan Winoto', 'nik' => '18000139', 'email' => 'edi_kurniawan@pinusmerahabadi.co.id'),
            229 => array('name' => 'Dadan Andriyanto', 'username' => 'Dadan Adryanto', 'nik' => '20150469', 'email' => 'dadan_andriyanto@pinusmerahabadi.co.id'),
            230 => array('name' => 'Yabes M Timu', 'username' => 'Yabes M Timu', 'nik' => '20173062', 'email' => 'yabes_timu@pinusmerahabadi.co.id'),
            231 => array('name' => 'Randy Syaputra', 'username' => 'Randy Syaputra', 'nik' => '20171777', 'email' => 'randy_syaputra@pinusmerahabadi.co.id'),
            232 => array('name' => 'Lesmana', 'username' => 'Lesmana', 'nik' => '20160819', 'email' => 'lesmana@pinusmerahabadi.co.id'),
            233 => array('name' => 'Fitri Ani', 'username' => 'Fitri Ani', 'nik' => '20180527', 'email' => 'fitri_ani@pinusmerahabadi.co.id'),
            234 => array('name' => 'Hendiyansyah', 'username' => 'Hendiyansyah', 'nik' => '20160919', 'email' => 'hendiyansyah@pinusmerahabadi.co.id'),
            235 => array('name' => 'Ramlan Saleh', 'username' => 'Ramlan Saleh', 'nik' => '19000232', 'email' => 'ramlan_saleh@pinusmerahabadi.co.id'),
            236 => array('name' => 'Sri Yanti', 'username' => 'Sri Yanti', 'nik' => '20161199', 'email' => 'Sri_yanti@pinusmerahabadi.co.id'),
            237 => array('name' => 'Ogie Herdyana', 'username' => 'Ogie Herdyana', 'nik' => '20171015', 'email' => 'ogie_herdyana@pinusmerahabadi.co.id'),
            238 => array('name' => 'Rizka Asri Dwi Putra', 'username' => 'Rizka Asri Dwi Putra', 'nik' => '20211029', 'email' => 'rizka_asri@pinusmerahabadi.co.id'),
            239 => array('name' => 'Rindi Nilasari', 'username' => 'Rindi Nila Sari', 'nik' => '20182557', 'email' => 'rindi_nila@pinusmerahabadi.co.id'),
            240 => array('name' => 'Rika Puspitasari', 'username' => 'Rika Puspita', 'nik' => '20172965', 'email' => 'rika_puspitasari@pinusmerahabadi.co.id'),
            241 => array('name' => 'Catur Setyo Nugroho', 'username' => 'Catur Setyo', 'nik' => '20150632', 'email' => 'Catur_setyo@pinusmerahabadi.co.id'),
            242 => array('name' => 'Aries Setiawan', 'username' => 'Aries Setiawan', 'nik' => '19000122', 'email' => 'aries_setiawan@pinusmerahabadi.co.id'),
            243 => array('name' => 'Reza Adypratama', 'username' => 'Reza Adypratama', 'nik' => '16000026', 'email' => 'reza_adypratama@pinusmerahabadi.co.id'),
            244 => array('name' => 'Lilik Aulia Subiawijaya', 'username' => 'Lilik Aulia Subiawijaya', 'nik' => '17000181', 'email' => 'lilik_wijaya@pinusmerahabadi.co.id'),
            245 => array('name' => 'Restu Iman Nugroho', 'username' => 'Restu', 'nik' => '20170858', 'email' => 'restu_iman@pinusmerahabadi.co.id'),
            246 => array('name' => 'Lim Steffi Halim', 'username' => 'Lim Steffi Halim', 'nik' => '20211780', 'email' => 'steffi_halim@pinusmerahabadi.co.id'),
            247 => array('name' => 'Michael Setia Budi', 'username' => 'Michael Setia Budi', 'nik' => '20000228', 'email' => 'michael_setia@pinusmerahabadi.co.id'),
            248 => array('name' => 'Ancelina Tandi Pareta', 'username' => 'Ancelina', 'nik' => '20191039', 'email' => 'Ancelina_tandi@pinusmerahabadi.co.id'),
            249 => array('name' => 'Edy Sutiady M', 'username' => 'Edy Sutiady', 'nik' => '20151309', 'email' => 'Edy_sutiady@pinusmerahabadi.co.id'),
            250 => array('name' => 'Christopher Yap Manampiring', 'username' => 'Christoper Yap', 'nik' => '17000601', 'email' => 'christopher_yap@pinusmerahabadi.co.id'),
            251 => array('name' => 'Haris Dibrata', 'username' => 'Haris Dibrata', 'nik' => '16000502', 'email' => 'haris_dibrata@pinusmerahabadi.co.id'),
            252 => array('name' => 'DWI SETYA RAHARJO', 'username' => 'Dwi Setya', 'nik' => '16000377', 'email' => 'dwi_setya@pinusmerahabadi.co.id'),
            253 => array('name' => 'Hengky Chandra', 'username' => 'Hengky Chandra', 'nik' => '05130026', 'email' => 'hengky_chandra@pinusmerahabadi.co.id'),
            254 => array('name' => 'Febe Priska P.', 'username' => 'Febe Priska', 'nik' => '20160827', 'email' => 'febe_priska@pinusmerahabadi.co.id'),
            255 => array('name' => 'Yulianto', 'username' => 'Yulianto', 'nik' => '20171820', 'email' => 'yulianto@pinusmerahabadi.co.id'),
            256 => array('name' => 'M. MaRuf Murtadho Arromdhany', 'username' => 'M. MaRuf Murtadho Arromdhany', 'nik' => '20130232', 'email' => 'maruf_murtadlo@pinusmerahabadi.co.id'),
            257 => array('name' => 'Bakti Indra Khanafi', 'username' => 'Bakti Indra', 'nik' => '20182664', 'email' => 'bakti_indra@pinusmerahabadi.co.id'),
            258 => array('name' => 'Louis Noviawati', 'username' => 'Louis Noviawati', 'nik' => '18000581', 'email' => 'louis_noviawati@pinusmerahabadi.co.id'),
            259 => array('name' => 'Dwi Setyo Virgianto', 'username' => 'Dwi Setyo Virgianto', 'nik' => '20163730', 'email' => 'dwi_setyo@pinusmerahabadi.co.id'),
            260 => array('name' => 'Khoirun Nissa', 'username' => 'Khoirun Nissa', 'nik' => '20180021', 'email' => 'khoirun_nissa@pinusmerahabadi.co.id'),
            261 => array('name' => 'Parlindungan Siregar', 'username' => 'Parlindungan', 'nik' => '08140347', 'email' => 'parlindungan_siregar@pinusmerahabadi.co.id'),
            262 => array('name' => 'Ricky Wahyu Kurniawan', 'username' => 'Ricky Wahyu K', 'nik' => '18000146', 'email' => 'riky_kurniawan@pinusmerahabadi.co.id'),
            263 => array('name' => 'Siswo Suwarjono', 'username' => 'Siswo Suwarjono', 'nik' => '05130051', 'email' => 'siswo_suwarjono@pinusmerahabadi.co.id'),
            264 => array('name' => 'Imat Rahmat Selamat', 'username' => 'Imat Rahmat Selamat', 'nik' => '20130067', 'email' => 'imat_ruhimat@pinusmerahabadi.co.id'),
            265 => array('name' => 'Rosanah', 'username' => 'Rosanah', 'nik' => '20180652', 'email' => 'rosanah@pinusmerahabadi.co.id'),
            266 => array('name' => 'Alyan Bin Mussa', 'username' => 'Alyan Bin Musa', 'nik' => '20180141', 'email' => 'alyan_mussa@pinusmerahabadi.co.id'),
            267 => array('name' => 'Anthonius Stefen Awuy', 'username' => 'Antonius Stefen Awuy', 'nik' => '19000352', 'email' => 'anthonius_stefan@pinusmerahabadi.co.id'),
            268 => array('name' => 'Presly Mayrendi Rembet', 'username' => 'Presly Mayrendi Rembet', 'nik' => '20215041', 'email' => 'presly_mayrendi@pinusmerahabadi.co.id'),
            269 => array('name' => 'Sri Wulandari', 'username' => 'Sri Wulandari', 'nik' => '20191205', 'email' => 'sri_wulandari@pinusmerahabadi.co.id'),
            270 => array('name' => 'Rizqan', 'username' => 'Rizqan', 'nik' => '20180985', 'email' => 'rizqan@pinusmerahabadi.co.id'),
            271 => array('name' => 'Gusti Ayu Mulya Nengsi', 'username' => 'Gusti Ayu Mulya Nengsi', 'nik' => '20181009', 'email' => 'gusti_ayu@pinusmerahabadi.co.id'),
            272 => array('name' => 'Wiwik Astuti Buranda', 'username' => 'Wiwik Astuti Buranda', 'nik' => '20213927', 'email' => 'wiwik_astuti@pinusmerahabadi.co.id'),
            273 => array('name' => 'Bima Putra Hutama', 'username' => 'Bima Putra', 'nik' => '20203364', 'email' => 'bima_putra@pinusmerahabadi.co.id'),
            274 => array('name' => 'Adi Yuda Prawira', 'username' => 'Adi Yuda Prawira', 'nik' => '20151151', 'email' => 'adi_yuda@pinusmerahabadi.co.id'),
            275 => array('name' => 'Suhandi', 'username' => 'Suhandi', 'nik' => '16000184', 'email' => 'suhandi@pinusmerahabadi.co.id'),
            276 => array('name' => 'Dedy Wahyu Setiana', 'username' => 'Dedy Wahyu Setiana', 'nik' => '20202574', 'email' => 'dedy_wahyu@pinusmerahabadi.co.id'),
            277 => array('name' => 'Dwi Tika Pratiwi', 'username' => 'Dwi Tika Pratiwi', 'nik' => '20150676', 'email' => 'dwi_tika@pinusmerahabadi.co.id'),
            278 => array('name' => 'Yohanes', 'username' => 'Yohanes', 'nik' => '08140681', 'email' => 'yohanes@pinusmerahabadi.co.id'),
            279 => array('name' => 'Mariance Bukit', 'username' => 'Mariance Bukit', 'nik' => '17000244', 'email' => 'mariance_bukit@pinusmerahabadi.co.id'),
            280 => array('name' => 'Hendry Chandra', 'username' => 'Hendry Chandra', 'nik' => '18000209', 'email' => 'hendry_chandra@pinusmerahabadi.co.id'),
            281 => array('name' => 'Esan', 'username' => 'Esan Tjong', 'nik' => '17000825', 'email' => 'esan_tjong@pinusmerahabadi.co.id'),
            282 => array('name' => 'Mira Kumala Sari', 'username' => 'Mira Kumala Sari', 'nik' => '20160126', 'email' => 'mira_kumala@pinusmerahabadi.co.id'),
            283 => array('name' => 'Kristin Novita Gultom', 'username' => 'Kristin Novita Gultom', 'nik' => '16000329', 'email' => 'kristin_gultom@pinusmerahabadi.co.id'),
            284 => array('name' => 'Joni', 'username' => 'Joni', 'nik' => '15000163', 'email' => 'joni_thio@pinusmerahabadi.co.id'),
            285 => array('name' => 'Suryanto', 'username' => 'Suryanto', 'nik' => '15000403', 'email' => 'suryanto@pinusmerahabadi.co.id'),
            286 => array('name' => 'Iwan', 'username' => 'Iwan Ang', 'nik' => '16000030', 'email' => 'iwan_ang@pinusmerahabadi.co.id'),
            287 => array('name' => 'Suhardi Ong', 'username' => 'Suhardi Ong', 'nik' => '18000818', 'email' => 'suhardi_ong@pinusmerahabadi.co.id'),
            288 => array('name' => 'M Fadli', 'username' => 'Muhammad Fadli', 'nik' => '20191565', 'email' => 'muhammad_fadli@pinusmerahabadi.co.id'),
            289 => array('name' => 'Rohmah Fauziah', 'username' => 'Rohmah Fauziah', 'nik' => '20210984', 'email' => 'rohmah_fauziah@pinusmerahabadi.co.id'),
            290 => array('name' => 'Redinetyas Prakasa Wibawa', 'username' => 'Redinetyas Prakasa Wibawa', 'nik' => '20150893', 'email' => 'redinetyas_prakasa@pinusmerahabadi.co.id'),
            291 => array('name' => 'Yonathan Marchelin Charles', 'username' => 'Yonathan Marchelin Charles', 'nik' => '16000378', 'email' => 'yonathan_marchelin@pinusmerahabadi.co.id'),
            292 => array('name' => 'Andika Yudi Darma', 'username' => 'Andika Yudi Darma', 'nik' => '20140702', 'email' => 'andika_yudi@pinusmerahabadi.co.id'),
            293 => array('name' => 'Ponda Saputra', 'username' => 'Ponda Saputra', 'nik' => '20210563', 'email' => 'ponda_saputra@pinusmerahabadi.co.id'),
            294 => array('name' => 'Helmy Alam Maulana', 'username' => 'Helmy Alam Maulana', 'nik' => '20172913', 'email' => 'helmy_maulana@pinusmerahabadi.co.id'),
            295 => array('name' => 'Hasan Basri Harefa', 'username' => 'Hasan Basri Harefa', 'nik' => '16000167', 'email' => 'hasan_basri@pinusmerahabadi.co.id'),
            296 => array('name' => 'Eka Sarnela', 'username' => 'Eka Sarnela', 'nik' => '20170506', 'email' => 'eka_sarnela@pinusmerahabadi.co.id'),
            297 => array('name' => 'Novi Yanti', 'username' => 'Novi Yanti', 'nik' => '20150316', 'email' => 'novi_yanti@pinusmerahabadi.co.id'),
            298 => array('name' => 'Winda Nurzanna Rambe', 'username' => 'Winda Nurzanna Rambe', 'nik' => '20171785', 'email' => 'winda_nurzanna@pinusmerahabadi.co.id'),
            299 => array('name' => 'Wirhan', 'username' => 'Wirhan', 'nik' => '18000999', 'email' => 'wirhan@pinusmerahabadi.co.id'),
            300 => array('name' => 'Ria Panca Putri', 'username' => 'Ria Panca Putri', 'nik' => '17000123', 'email' => 'ria_putri@pinusmerahabadi.co.id'),
            301 => array('name' => 'Soneta Iman', 'username' => 'Soneta Iman', 'nik' => '16000087', 'email' => 'soneta_iman@pinusmerahabadi.co.id'),
            302 => array('name' => 'Elwandi', 'username' => 'Elwandi', 'nik' => '20160509', 'email' => 'elwandi@pinusmerahabadi.co.id'),
            303 => array('name' => 'Fathurrohman', 'username' => 'Fathurrohman', 'nik' => '17000251', 'email' => 'fathurrohman@pinusmerahabadi.co.id'),
            304 => array('name' => 'William', 'username' => 'William Wong', 'nik' => '19000262', 'email' => 'william_wong@pinusmerahabadi.co.id'),
            305 => array('name' => 'Oryan Oktorio', 'username' => 'Oryan Oktorio', 'nik' => '16000073', 'email' => 'oryan_oktorio@pinusmerahabadi.co.id'),
            306 => array('name' => 'Isyura Elisabeth Surbakti', 'username' => 'Isyura Elisabeth Surbakti', 'nik' => '20161837', 'email' => 'isyura_elisabeth@pinusmerahabadi.co.id'),
            307 => array('name' => 'Niko Apvianto', 'username' => 'Niko Apvianto', 'nik' => '17000602', 'email' => 'niko_apvianto@pinusmerahabadi.co.id'),
            308 => array('name' => 'Yuli Sumarni', 'username' => 'Yuli Sumarni', 'nik' => '20180833', 'email' => 'yuli_sumarni@pinusmerahabadi.co.id'),
            309 => array('name' => 'Yosita Fasilia Bira', 'username' => 'Yosita Fasilia Bira', 'nik' => '20213619', 'email' => 'yosita_fasilia@pinusmerahabadi.co.id'),
            310 => array('name' => 'Albar Simu Faalu', 'username' => 'Albar Faalu', 'nik' => '20000196', 'email' => 'albar_faalu@pinusmerahabadi.co.id'),
            311 => array('name' => 'Ilna', 'username' => 'Ilna', 'nik' => '20151181', 'email' => 'ilna@pinusmerahabadi.co.id'),
            312 => array('name' => 'Winda Nusaly', 'username' => 'Winda Nusaly', 'nik' => '16000382', 'email' => 'winda_nusaly@pinusmerahabadi.co.id'),
            313 => array('name' => 'Yoga Septiansyah', 'username' => 'Yoga Septiansyah', 'nik' => '20191860', 'email' => 'yoga_septiansyah@pinusmerahabadi.co.id'),
            314 => array('name' => 'Erra Apriyanto', 'username' => 'Erra Apriyanto', 'nik' => '20160299', 'email' => 'erra_apriyanto@pinusmerahabadi.co.id'),
            315 => array('name' => 'Sholihuddin', 'username' => 'Sholihuddin', 'nik' => '21000162', 'email' => 'sholihuddin@pinusmerahabadi.co.id'),
            316 => array('name' => 'Ana Syukriyah', 'username' => 'Ana Syukriyah', 'nik' => '20202536', 'email' => 'ana_syukriyah@pinusmerahabadi.co.d'),
            317 => array('name' => 'Yuliana', 'username' => 'Yuliana', 'nik' => '20202910', 'email' => 'yuliana@pinusmerahabadi.co.id'),
            318 => array('name' => 'Tety Dwi Oktaviana', 'username' => 'Tety Dwi Oktaviana', 'nik' => '20173138', 'email' => 'dwi_oktaviana@pinusmerahabadi.co.id'),
            319 => array('name' => 'Nurul Setyaningrum', 'username' => 'Nurul Setyaningrum', 'nik' => '20181957', 'email' => 'nurul_setyaningrum@pinusmerahabadi.co.id'),
            320 => array('name' => 'Suka Herlina', 'username' => 'Suka Herlina', 'nik' => '20183590', 'email' => 'suka_herlina@pinusmerahabadi.co.id'),
            321 => array('name' => 'Al Rajanur Musbar', 'username' => 'Rajanur', 'nik' => '20173751', 'email' => 'rajanur_musbar@pinusmerahabadi.co.id'),
            322 => array('name' => 'Akhmat Syahrul', 'username' => 'Akhmat Syahrul', 'nik' => '20203211', 'email' => 'akhmat_syahrul@pinusmerahabadi.co.id'),
            323 => array('name' => 'Sri Dewiyanti', 'username' => 'Sri Dewiyanti', 'nik' => '20191998', 'email' => 'sri_dewiyanti@pinusmerahabadi.co.id'),
            324 => array('name' => 'Hendry Syam', 'username' => 'Hendry Syam', 'nik' => '21000206', 'email' => 'hendry_syam@pinusmerahabadi.co.id'),
            325 => array('name' => 'Iskandar Wahidyat', 'username' => 'Iskandar Wahidyat', 'nik' => '20212181', 'email' => 'iskandar_wahidyat@pinusmerahabadi.co.id'),
            326 => array('name' => 'Dwi Yunianto', 'username' => 'Dwi Yunianto', 'nik' => '20163398', 'email' => 'dwi_yunianto@pinusmerahabadi.co.id'),
            327 => array('name' => 'Pera Rahmi Putri', 'username' => 'Pera Rahmi Putri', 'nik' => '20191771', 'email' => 'pera_rahmi@pinusmerahabadi.co.id'),
            328 => array('name' => 'Hugo Paulus Lamera', 'username' => 'Hugo Paulus Lamera', 'nik' => '20172737', 'email' => 'hugo_paulus@pinusmerahabadi.co.id'),
            329 => array('name' => 'Randi Mulya', 'username' => 'Randi Mulya', 'nik' => '20173771', 'email' => 'randi_mulya@pinusmerahabadi.co.id'),
            330 => array('name' => 'Awit Slamet Darmanto', 'username' => 'Awit Slamet', 'nik' => '20150166', 'email' => 'awit_slamet@pinusmerahabadi.co.id'),
            331 => array('name' => 'Dio Alif Pratama', 'username' => 'Dio Alif', 'nik' => '18001007', 'email' => 'dio_alif@pinusmerahabadi.co.id'),
            332 => array('name' => 'Johnson', 'username' => 'Johnson', 'nik' => '19000308', 'email' => 'johnson@pinusmerahabadi.co.id'),
            333 => array('name' => 'Daniel Asalim', 'username' => 'Daniel Asalim', 'nik' => '21000278', 'email' => 'daniel_salim@pinusmerahabadi.co.id'),
            334 => array('name' => 'Musbichin', 'username' => 'Musbichin', 'nik' => '20182483', 'email' => 'musbichin@pinusmerahabadi.co.id'),
            335 => array('name' => 'Ginta Arganata', 'username' => 'Ginta Arganata', 'nik' => '16000383', 'email' => 'ginta_arganata@pinusmerahabadi.co.id'),
            336 => array('name' => 'Rinto Afriadi', 'username' => 'Rinto Afriadi', 'nik' => '20150240', 'email' => 'Rinto_afriadi@pinusmerahabadi.co.id'),
            337 => array('name' => 'Heri Hendawan', 'username' => 'Heri Hendawan', 'nik' => '16000277', 'email' => 'heri_hendawan@pinusmerahabadi.co.id'),
            338 => array('name' => 'Karyo', 'username' => 'Karyo', 'nik' => '08130787', 'email' => 'karyo@pinusmerahabadi.co.id'),
            339 => array('name' => 'Fachrul Fauzi', 'username' => 'Fachrul Fauzi', 'nik' => '18000145', 'email' => 'fachrul_fauzy@pinusmerahabadi.co.id'),
            340 => array('name' => 'Sarif Abdullah', 'username' => 'Sarif Abdullah', 'nik' => '20171125', 'email' => 'sarif_abdullah@pinusmerahabadi.co.id'),
            341 => array('name' => 'Agus Widodo', 'username' => 'Agus Widodo', 'nik' => '20171294', 'email' => 'agus_widodo@pinusmerahabadi.co.id'),
            342 => array('name' => 'Karlina', 'username' => 'Karlina', 'nik' => '20181250', 'email' => 'karlina@pinusmerahabadi.co.id'),
            343 => array('name' => 'Antonius', 'username' => 'Antonius', 'nik' => '20000071', 'email' => 'antonius_liu@pinusmerahabadi.co.id'),
            344 => array('name' => 'Ferbiyan Grafiani D', 'username' => 'Ferbiyan Grafiani D', 'nik' => '20180236', 'email' => 'ferbiyan_grafiani@pinusmerahabadi.co.id'),
            345 => array('name' => 'Sucito', 'username' => 'Sucito', 'nik' => '17000597', 'email' => 'sucito@pinusmerahabadi.co.id'),
            346 => array('name' => 'Johan Avendi', 'username' => 'Johan Avendi', 'nik' => '17000186', 'email' => 'johan_avendi@pinusmerahabadi.co.id'),
            347 => array('name' => 'Alan Rully Kusuma', 'username' => 'Alan Rully Kusuma', 'nik' => '20170651', 'email' => 'alan_rully@pinusmerahabadi.co.id'),
            348 => array('name' => 'Ke vin', 'username' => 'Kevin', 'nik' => '19000252', 'email' => 'ke_vin@pinusmerahabadi.co.id'),
            349 => array('name' => 'Fatoni Kurniawan', 'username' => 'Fatoni Kurniawan', 'nik' => '20151076', 'email' => 'fatoni_kurniawan@pinusmerahabadi.co.id'),
            350 => array('name' => 'Ria Restuni', 'username' => 'Ria Restuni', 'nik' => '20160669', 'email' => 'ria_restuni@pinusmerahabadi.co.id'),
            351 => array('name' => 'Lilis Sunaryaningsih', 'username' => 'Lilis Sunaryaningsih', 'nik' => '20140225', 'email' => 'lilis_sunaryaningsih@pinusmerahabadi.co.id'),
            352 => array('name' => 'Zulkifli', 'username' => 'Zulkifli', 'nik' => '16000212', 'email' => 'zulkifli_kamil@pinusmerahabadi.co.id'),
            353 => array('name' => 'Samidi', 'username' => 'Samidi', 'nik' => '20173678', 'email' => 'samidi@pinusmerahabadi.co.id'),
            354 => array('name' => 'Ujang Arifin', 'username' => 'Ujang Arifin', 'nik' => '20130108', 'email' => 'ujang_arifin@pinusmerahabadi.co.id'),
            355 => array('name' => 'Malvin Setiawan', 'username' => 'Malvin Setiawan', 'nik' => '19000191', 'email' => 'malvin_setiawan@pinusmerahabadi.co.id'),
            356 => array('name' => 'Retno Setyowati', 'username' => 'Retno S', 'nik' => '20150347', 'email' => 'retno_setyowati@pinusmerahabadi.co.id'),
            357 => array('name' => 'Heri Subekti', 'username' => 'Heri Subekti', 'nik' => '20150212', 'email' => 'heri_subekti@pinusmerahabadi.co.id'),
            358 => array('name' => 'Slamet Gunawan', 'username' => 'Slamet Gunawan', 'nik' => '08130980', 'email' => 'slamet_gunawan@pinusmerahabadi.co.id'),
            359 => array('name' => 'Lukas Mulyanto', 'username' => 'Lukas Mulyanto', 'nik' => '18000316', 'email' => 'lukas_mulyanto@pinusmerahabadi.co.id'),
            360 => array('name' => 'Bayu Wng', 'username' => 'Bayu Wng', 'nik' => '20140588', 'email' => 'bayu_wng@pinusmerahabadi.co.id'),
            361 => array('name' => 'Muhammad Arbaini', 'username' => 'M. Arbaini', 'nik' => '20192066', 'email' => 'muhammad_arbaini@pinusmerahabadi.co.id'),
            362 => array('name' => 'Pandapotan S.L. Batubara', 'username' => 'Pandapotan S.L. Batubara', 'nik' => '20161676', 'email' => 'panda_batubara@pinusmerahabadi.co.id'),
            363 => array('name' => 'Koermardian Wongli', 'username' => 'Koermardian Wongli', 'nik' => '19000194', 'email' => 'koermardian_wongli@pinusmerahabadi.co.id'),
            364 => array('name' => 'Minahari', 'username' => 'Minahari', 'nik' => '20180721', 'email' => 'Minahari@pinusmerahabadi.co.id'),
            365 => array('name' => 'Dede Setiana', 'username' => 'Dede Setiana', 'nik' => '20173386', 'email' => 'dede_setiana@pinusmerahabadi.co.id'),
            366 => array('name' => 'Yusuf Eko Andiyanto', 'username' => 'Yusuf Eko', 'nik' => '20160445', 'email' => 'Yusuf_eko@pinusmerahabadi.co.id'),
            367 => array('name' => 'Wiwin Dwi Ningsih', 'username' => 'Wiwin Dwi Ningsih', 'nik' => '20163863', 'email' => 'wiwin_dwiningsih@pinusmerahabadi.co.id'),
            368 => array('name' => 'Roby Rachmad', 'username' => 'Roby Rachmad', 'nik' => '15000258', 'email' => 'roby_rachmad@pinusmerahabadi.co.id'),
            369 => array('name' => 'Dodo Triyo Pramono', 'username' => 'Dodo Triyo', 'nik' => '20000070', 'email' => 'dodo_triyo@pinusmerahabadi.co.id'),
            370 => array('name' => 'Rahmatina Duha', 'username' => 'Rahmatina Duha', 'nik' => '20171573', 'email' => 'rahmatina_duha@pinusmerahabadi.co.id'),
            371 => array('name' => 'Adriel Leonardo Kotte', 'username' => 'Adriel Leonardo Kotte', 'nik' => '20212634', 'email' => 'adriel_leonardo@pinusmerahabadi.co.id'),
            372 => array('name' => 'Gilar Singgih Sutandi', 'username' => 'Gilar Singgih Sutandi', 'nik' => '20160285', 'email' => 'gilar_singgih@pinusmerahabadi.co.id'),
            373 => array('name' => 'Sapitri Suryanti', 'username' => 'Sapitri Suryanti', 'nik' => '20180918', 'email' => 'sapitri_suryanti@pinusmerahabadi.co.id'),
            374 => array('name' => 'Anton Tonapa', 'username' => 'Anton Tonapa', 'nik' => '05130087', 'email' => 'anton_tonapa@pinusmerahabadi.co.id'),
            375 => array('name' => 'Stefan Timotheus Panjaitan', 'username' => 'Stefan Timotheus', 'nik' => '20203644', 'email' => 'stefan_timotheus@pinusmerahabadi.co.id'),
            376 => array('name' => 'Dina Septiani', 'username' => 'Dina Septiani', 'nik' => '20191837', 'email' => 'dina_septiani@pinusmerahabadi.co.id'),
            377 => array('name' => 'Abdul Hamid Fauzi', 'username' => 'Abdul Hamid Fauzi', 'nik' => '20171239', 'email' => 'abdul_hamid@pinusmerahabadi.co.id'),
            378 => array('name' => 'Rahmat Suharyadi', 'username' => 'Rahmad S', 'nik' => '20150346', 'email' => 'rahmad_suharyadi@pinusmerahabadi.co.id'),
            379 => array('name' => 'Heru Pramono', 'username' => 'Heru Pramono', 'nik' => '16000075', 'email' => 'heru_pramono@pinusmerahabadi.co.id'),
            380 => array('name' => 'Eko Purwono', 'username' => 'Eko Purwono', 'nik' => '21000156', 'email' => 'eko_purwono@pinusmerahabadi.co.id'),
            381 => array('name' => 'Aloysius Christian Santoso', 'username' => 'Aloysius Christian Santoso', 'nik' => '16000509', 'email' => 'aloysius_christian@pinusmerahabadi.co.id'),
            382 => array('name' => 'Yulita Adrianto', 'username' => 'Ruth', 'nik' => '08130976', 'email' => 'yulita_adrianto@pinusmerahabadi.co.id'),
            383 => array('name' => 'Dadang Handoko', 'username' => 'Dadang Handoko', 'nik' => '20211209', 'email' => 'dadang_handoko@pinusmerahabadi.co.id'),
            384 => array('name' => 'Jumiyanto', 'username' => 'Jumiyanto', 'nik' => '20130250', 'email' => 'jumiyanto@pinusmerahabadi.co.id'),
            385 => array('name' => 'Rendy Tri Prasetyo', 'username' => 'Rendy Tri Prasetyo', 'nik' => '18000285', 'email' => 'Rendy_triprasetyo@pinusmerahabadi.co.id'),
            386 => array('name' => 'Bayu Anggoro', 'username' => 'Bayu Anggoro', 'nik' => '20181331', 'email' => 'bayu_anggoro@pinusmerahabadi.co.id'),
            387 => array('name' => 'Yohanes Kurniawan', 'username' => 'Yohanes Kurniawan', 'nik' => '18000750', 'email' => 'yohanes_kurniawan@pinusmerahabadi.co.id'),
            388 => array('name' => 'Hardiana', 'username' => 'Hardiana', 'nik' => '20180714', 'email' => 'hardiana@pinusmerahabadi.co.id'),
            389 => array('name' => 'Nelson Vernando', 'username' => 'Nelson Vernando', 'nik' => '20140597', 'email' => 'nelson_vernando@pinusmerahabadi.co.id'),
            390 => array('name' => 'Abdul Rozak', 'username' => 'Abdul Rozak', 'nik' => '08130559', 'email' => 'abdul_rozak@pinusmerahabadi.co.id'),
            391 => array('name' => 'Pramudya Ananta K.D', 'username' => 'Pramudya Ananta', 'nik' => '20140641', 'email' => 'pramudya_ananta@pinusmerahbadi.co.id'),
            392 => array('name' => 'Suryani Paulina', 'username' => 'Suryani Paulina', 'nik' => '20173244', 'email' => 'suryani_paulina@pinusmerahabadi.co.id'),
            393 => array('name' => 'Meynita Hadijah', 'username' => 'Meynita Hadijah', 'nik' => '20180263', 'email' => 'meynita_hadijah@pinusmerahabadi.co.id'),
            394 => array('name' => 'Desy Dewi Wulandari', 'username' => 'Desy Dewi Wulandari', 'nik' => '20160367', 'email' => 'desy_dewi@pinusmerahabadi.co.id'),
            395 => array('name' => 'Yovita Soviana Santoso', 'username' => 'Yovita Soviana Santoso', 'nik' => '17000486', 'email' => 'yovita_soviana@pinusmerahabadi.co.id'),
            396 => array('name' => 'Tjeng Yanata Chandra', 'username' => 'Yanata Chandra', 'nik' => '17000752', 'email' => 'yanata_chandra@pinusmerahabadi.co.id'),
            397 => array('name' => 'I Gusti Ngurah Adhi Praditya', 'username' => 'I Gusti Ngurah Adhi Praditya', 'nik' => '20170052', 'email' => 'adhi_praditya@pinusmerahabadi.co.id'),
            398 => array('name' => 'Elvryda Marthalena', 'username' => 'Elvryda Marthalena', 'nik' => '20161007', 'email' => 'elvryda_marthalena@pinusmerahabadi.co.id'),
            399 => array('name' => 'Musa', 'username' => 'Musa', 'nik' => '20170122', 'email' => 'musa_log@pinusmerahabadi.co.id'),
            400 => array('name' => 'Estu Nur Hare Latul Suhenda', 'username' => 'Estu Nur Hare Latul Suhenda', 'nik' => '20161902', 'email' => 'estu_nur@pinusmerahabadi.co.id'),
            401 => array('name' => 'Bachtiar Adi Nugroho', 'username' => 'Bachtiar Adi N', 'nik' => '20172141', 'email' => 'bachtiar_adi@pinusmerahabadi.co.id'),
            402 => array('name' => 'Fx Uky Aprianto', 'username' => 'Fx Uky Aprianto', 'nik' => '16000511', 'email' => 'uky_aprianto@pinusmerahabadi.co.id'),
            403 => array('name' => 'Ronny Satria Abadi', 'username' => 'Ronny Satria Abadi', 'nik' => '17000365', 'email' => 'ronny_satria@pinusmerahabadi.co.id'),
            404 => array('name' => 'Heny Purbo Rekno', 'username' => 'Heny Purbo Rekno', 'nik' => '20211030', 'email' => 'heny_purbo@pinusmerahabadi.co.id'),
            405 => array('name' => 'Fadli Richardo', 'username' => 'Fadli Ricardo', 'nik' => '20170459', 'email' => 'fadli_richardo@pinusmerahabadi.co.id'),
            406 => array('name' => 'Maidoli Candra', 'username' => 'Maidoli', 'nik' => '17000178', 'email' => 'maidoli_candra@pinusmerahabadi.co.id'),
            407 => array('name' => 'Meidiana Putri', 'username' => 'Meidiana Putri', 'nik' => '20180984', 'email' => 'meidiana_putri@pinusmerahabadi.co.id'),
            408 => array('name' => 'Yuliyanto', 'username' => 'Yuliyanto', 'nik' => '20203448', 'email' => 'yuliyanto@pinusmerahabadi.co.id'),
            409 => array('name' => 'Ahmad Ichsan Yunanto', 'username' => 'Ahmad Ichsan Yunanto', 'nik' => '20180644', 'email' => 'ahmad_ichsan@pinusmerahabadi.co.id'),
            410 => array('name' => 'Aas Ariska', 'username' => 'Aas Ariska', 'nik' => '20140704', 'email' => 'aas_ariska@pinusmerahabadi.co.id'),
            411 => array('name' => 'Rosi Rosmawati Dewi', 'username' => 'Rosi Rosmawati Dewi', 'nik' => '20130379', 'email' => 'rosi_dewi@pinusmerahabadi.co.id'),
            412 => array('name' => 'Diana Wijaya', 'username' => 'Diana Wijaya', 'nik' => '19000234', 'email' => 'diana_wijaya@pinusmerahabadi.co.id'),
            413 => array('name' => 'Chandra Hidayat', 'username' => 'Chandra Hidayat', 'nik' => '17000188', 'email' => 'chandra_hidayat@pinusmerahabadi.co.id'),
            414 => array('name' => 'Boyke Heru Hadian', 'username' => 'Boyke Heru', 'nik' => '08141323', 'email' => 'boyke_heru@pinusmerahabadi.co.id'),
            415 => array('name' => 'Asep Gatot Suhendra', 'username' => 'Asep Gatot Suhendra', 'nik' => '20151979', 'email' => 'asep_gator@pinusmerahabadi.co.id'),
            416 => array('name' => 'Qurrotul Uyun', 'username' => 'Qurrotul Uyun', 'nik' => '20170845', 'email' => 'qurrotul_uyun@pinusmerahabadi.co.id'),
            417 => array('name' => 'Nur Fadly', 'username' => 'Nur Fadly', 'nik' => '20162106', 'email' => 'nur_fadly@pinusmerahabadi.co.id'),
            418 => array('name' => 'Saiyed Opu', 'username' => 'Saiyed Opu', 'nik' => '16000275', 'email' => 'saiyed_opu@pinusmerahabadi.co.id'),
            419 => array('name' => 'Erik Setaaji', 'username' => 'Erik Setaaji', 'nik' => '20163111', 'email' => 'erik_setaaji@pinusmerahabadi.co.id'),
            420 => array('name' => 'Bimo Prakoso', 'username' => 'Bimo Prakoso', 'nik' => '20162904', 'email' => 'bimo_prakoso@pinusmerahabadi.co.id'),
            421 => array('name' => 'Lianawati', 'username' => 'Lianawati', 'nik' => '16000510', 'email' => 'lianawati@pinusmerahabadi.co.id'),
            422 => array('name' => 'Ruswan Suryadi', 'username' => 'Ruswan', 'nik' => '16000249', 'email' => 'ruswan_suryadi@pinusmerahabadi.co.id'),
            423 => array('name' => 'Arief Indra Tjahjono', 'username' => 'Arief Indra', 'nik' => '05130039', 'email' => 'arief_indra@pinusmerahabadi.co.id'),
            424 => array('name' => 'Made Agus Wiyadnyana', 'username' => 'Made Agus Wiyadnyana', 'nik' => '20150149', 'email' => 'gede_aris@pinusmerahabadi.co.id'),
            425 => array('name' => 'Alfianto', 'username' => 'Alfianto', 'nik' => '20180054', 'email' => 'alfianto@pinusmerahabadi.co.id'),
            426 => array('name' => 'Rajip Priatno', 'username' => 'Rajip Priatno', 'nik' => '20163178', 'email' => 'rajip_priatno@pinusmerahabadi.co.id'),
            427 => array('name' => 'Muhammad Hairudin', 'username' => 'M. Hairudin', 'nik' => '20180084', 'email' => 'muhammad_hairudin@pinusmerahabadi.co.id'),
            428 => array('name' => 'Ika Nuraini', 'username' => 'Ika Nuraini', 'nik' => '20180047', 'email' => 'ika_nuraini@pinusmerahabadi.co.id'),
            429 => array('name' => 'Al Achyar Permana Putra', 'username' => 'Al Achyar Permana Putra', 'nik' => '20182670', 'email' => 'achyar_permana@pinusmerahabadi.co.id'),
            430 => array('name' => 'Ari Wardoyo', 'username' => 'Ari Wardoyo', 'nik' => '16000506', 'email' => 'ari_wardoyo@pinusmerahabadi.co.id'),
            431 => array('name' => 'Muhamad Syehabbuddin', 'username' => 'Muhamad Syehabbuddin', 'nik' => '20180147', 'email' => 'muhammad_syehabbuddin@pinusmerahabadi.co.id'),
            432 => array('name' => 'Ali Gunawan', 'username' => 'Ali Gunawan', 'nik' => '20000163', 'email' => 'ali_gunawan@pinusmerahabadi.co.id'),
            433 => array('name' => 'Siti Hatimah Rahmadaniah', 'username' => 'Siti Hatimah Rahmadaniah', 'nik' => '20212554', 'email' => 'siti_hatimah@pinusmerahabadi.co.id'),
            434 => array('name' => 'Mawan Hermawan', 'username' => 'Mawan Hermawan', 'nik' => '20140530', 'email' => 'mawan_hermawan@pinusmerahabadi.co.id'),
            435 => array('name' => 'Miranti Damayanti', 'username' => 'Miranti', 'nik' => '20130057', 'email' => 'miranti_damayanti@pinusmerahabadi.co.id'),
            436 => array('name' => 'Ivan Hartono', 'username' => 'Ivan Hartono', 'nik' => '20000195', 'email' => 'ivan_hartono@pinusmerahabadi.co.id'),
            437 => array('name' => 'Lilis Suryani', 'username' => 'Lilis Suryani', 'nik' => '20150157', 'email' => 'lilis_suryani@pinusmerahabadi.co.id'),
            438 => array('name' => 'Jeffry Djoko Soesanto', 'username' => 'Jeffry Djoko', 'nik' => '21000189', 'email' => 'jeffry_djoko@pinusmerahabadi.co.id'),
            439 => array('name' => 'Muchamad Yusup', 'username' => 'Muchamad Yusup', 'nik' => '20210200', 'email' => 'muchamad_yusup@pinusmerahabadi.co.id'),
            440 => array('name' => 'Rudi', 'username' => 'Rudi', 'nik' => '20150246', 'email' => 'rudi_maryadin@pinusmerahabadi.co.id'),
            441 => array('name' => 'Arya Aji Pratama', 'username' => 'Arya Ajie', 'nik' => '20150862', 'email' => 'arya_aji@pinusmerahabadi.co.id'),
            442 => array('name' => 'Mariana', 'username' => 'Mariana', 'nik' => '20170641', 'email' => 'mariana@pinusmerahabadi.co.id'),
            443 => array('name' => 'Tjoko Raharjo', 'username' => 'Tjoko Raharjo', 'nik' => '20162079', 'email' => 'macrg_sa@pinusmerahabadi.co.id'),
            444 => array('name' => 'Dikson Wibowo', 'username' => 'Dikson Wibowo', 'nik' => '16000507', 'email' => 'dikson_wibowo@pinusmerahabadi.co.id'),
            445 => array('name' => 'Novanda Rangga Dhiorama Putra', 'username' => 'Novanda Rangga Dhiorama Putra', 'nik' => '20180395', 'email' => 'novanda_rangga@pinusmerahabadi.co.id'),
            446 => array('name' => 'Akbar Hendra Kurniawan', 'username' => 'Akbar Hendra Kurniawan', 'nik' => '20173069', 'email' => 'akbar_hendra@pinusmerahabadi.co.id'),
            447 => array('name' => 'Eva Ekmawati', 'username' => 'Eva Ekmawati', 'nik' => '20160850', 'email' => 'eva_ekmawati@pinusmerahabadi.co.id'),
            448 => array('name' => 'Erfan Yulianto', 'username' => 'Erfan Yulianto', 'nik' => '20150408', 'email' => 'erfan_yulianto@pinusmerahabadi.co.id'),
            449 => array('name' => 'Arif Abdillah', 'username' => 'Arif Abdillah', 'nik' => '20162531', 'email' => 'arif_abdillah@pinusmerahabadi.co.id'),
            450 => array('name' => 'Tri Adh Hariyono', 'username' => 'Tri Adh', 'nik' => '20152091', 'email' => 'tri_hariyono@pinusmerahabadi.co.id'),
            451 => array('name' => 'Awali Andika Rahmawan M', 'username' => 'Awali Andika Rahmawan M', 'nik' => '20161064', 'email' => 'awali_andika@pinusmerahabadi.co.id'),
            452 => array('name' => 'Dewi Surahmini', 'username' => 'Dewi Surahmini', 'nik' => '20211907', 'email' => 'dewi_surahmini@pinusmerahabadi.co.id'),
            453 => array('name' => 'Muhammad Syafaat', 'username' => 'Muhammad Syafaat', 'nik' => '20140264', 'email' => 'muhammad_syafaat@pinusmerahabadi.co.id'),
            454 => array('name' => 'Shinta Permata Sari', 'username' => 'Shinta Permata', 'nik' => '20212295', 'email' => 'shinta_permata@pinusmerahabadi.co.id'),
            455 => array('name' => 'Muhammad Ismail', 'username' => 'Muhammad Ismail', 'nik' => '20161861', 'email' => 'muhammad_ismail@pinusmerahabadi.co.id'),
            456 => array('name' => 'Lazarus Feri Nugraha Dwi Diyanto', 'username' => 'L. Feri Nugraha', 'nik' => '15000333', 'email' => 'feri_nugraha@pinusmerahabadi.co.id'),
            457 => array('name' => 'Antonius ghani Dharmawan', 'username' => 'Antonius Darmawan', 'nik' => '15000218', 'email' => 'antonius_darmawan@pinusmerahabadi.co.id'),
            458 => array('name' => 'Eddy Muryanto', 'username' => 'Eddy Muryanto', 'nik' => '05130055', 'email' => 'eddy_muryanto@pinusmerahabadi.co.id'),
            459 => array('name' => 'Retna Dwi Palupi Wulandari', 'username' => 'Retna Dwi Palupi Wulandari', 'nik' => '20183595', 'email' => 'retna_dwi@pinusmerahabadi.co.id'),
            460 => array('name' => 'Prasetyo Budi Suyono', 'username' => 'Prasetyo Budi S', 'nik' => '20170162', 'email' => 'prasetyo_budi@pinusmerahabadi.co.id'),
            461 => array('name' => 'Shofa Adi Lukito', 'username' => 'Shofa Adi L', 'nik' => '20183815', 'email' => 'shofa_adi@pinusmerahabadi.co.id'),
            462 => array('name' => 'Jason Timothy Soetanto', 'username' => 'Jason Timothy', 'nik' => '18000289', 'email' => 'jason_timothy@pinusmerahabadi.co.id'),
            463 => array('name' => 'Asep Saputrawan', 'username' => 'Asep Saputrawan', 'nik' => '20220202', 'email' => 'asep_saputrawan@pinusmerahabadi.co.id'),
            464 => array('name' => 'Wandi Dimas Permana', 'username' => 'Wandi Dimas Permana', 'nik' => '20220028', 'email' => 'wandi_dimas@pinusmerahabadi.co.id'),
            465 => array('name' => 'Ningsih Dorlina', 'username' => 'Ningsih Dorlina', 'nik' => '20220043', 'email' => 'ningsih_dorlina@pinusmerahabadi.co.id'),
            466 => array('name' => 'Syarifuddin', 'username' => 'syarifuddin', 'nik' => '22000111', 'email' => 'syarifuddin@pinusmerahabadi.co.id')
        );
        foreach($data as $employee_data){
            try{
                $count_employee = Employee::withTrashed()->count() + 1;
                $code = "EMP-".str_repeat("0", 4-strlen($count_employee)).$count_employee;

                $checkEmployee = Employee::where('username',$employee_data["username"])->first();
                if($checkEmployee){
                    throw new \Exception("Username exists ".$employee_data['name']." | ".$employee_data['username']." | ".$employee_data['email']);
                }

                $checkEmployee = Employee::where('nik',$employee_data["nik"])->first();
                if($checkEmployee){
                    throw new \Exception("NIK exists ".$employee_data['name']." | ".$employee_data['username']." | ".$employee_data['email']);
                }
                // $checkEmployee = Employee::where('email',$employee_data["email"])->first();
                // if($checkEmployee){
                //     throw new \Exception("Email exists ".$employee_data['name']." | ".$employee_data['username']." | ".$employee_data['email']);
                // }

                if (!filter_var($employee_data['email'], FILTER_VALIDATE_EMAIL)) {
                    throw new \Exception("Email format false ".$employee_data['name']." | ".$employee_data['username']." | ".$employee_data['email']);
                }

                $newEmployee                         = new Employee;
                $newEmployee->code                   = $code;
                $newEmployee->name                   = $employee_data["name"];
                $newEmployee->username               = $employee_data["username"];
                $newEmployee->nik                    = $employee_data["nik"] ?? $employee_data["username"];
                $newEmployee->email                  = $employee_data["email"];
                $newEmployee->password               = Hash::make("pma123");
                $newEmployee->save();
            }catch(\Exception $ex){
                print($ex->getMessage()."\n");
            }
        }

        print("import employee data finished");
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}
